stages:
  - compile
  - build
  - push

compile:
  stage: compile
  image: maven:3.9.4-eclipse-temurin-17-alpine
  script:
    - ./mvnw clean package
  artifacts:
    paths:
      - target/*.jar

build:
  stage: build
  image: docker:24.0.6
  services:
    - docker:dind
  script:
    - ls -ltr target
    - docker build -t my-app-image .
  dependencies:
    - compile
