stages:
  - compile
  - build
  - push

compile:
  stage: compile
  image: maven:3.9.4-eclipse-temurin-17-alpine
  script:
    - ./mvnw clean package
  artifacts:
    paths:
      - target/*.jar

build:
  stage: build
  image: docker:24.0.6
  services:
    - docker:dind
  script:
    - ls -ltr target
    - docker build -t ithome-app-backend:main-v1 .
  dependencies:
    - compile


push:
  stage: push
  script:
    - docker tag ithome-app-backend:main-v1 yihonggaotw/ithome-app-backend:main-v1
    - docker push yihonggaotw/ithome-app-backend:main-v1
  dependencies:
    - build
