stages:
  - compile
  - build
  - push

variables:
  IMAGE_NAME: ithome-app-backend
  CI_IMAGE: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA

compile:
  stage: compile
  image: maven:3.9.4-eclipse-temurin-17-alpine
  script:
    - ./mvnw clean package
  artifacts:
    paths:
      - target/*.jar

build:
  stage: build
  image: docker:24.0.6
  services:
    - docker:dind
  script:
    - ls -ltr target
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:v1 .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:v1
  dependencies:
    - compile


push:
  stage: push
  image: docker:24.0.6
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE_NAME:v1
    - docker image ls
    - docker tag $CI_REGISTRY_IMAGE/$IMAGE_NAME:v1 yihonggaotw/$IMAGE_NAME:main-v1
    - docker push yihonggaotw/$IMAGE_NAME:main-v1
  dependencies:
    - build
