stages:
  - compile
  - build
  - push

compile:
  stage: compile
  image: maven:3.9.4-eclipse-temurin-17-alpine
  script:
    - ./mvnw clean package
  artifacts:
    paths:
      - target/*.jar

build:
  stage: build
  tags:
    - linux
    - docker
    - saas-linux-small-amd64
  script:
    - ls -ltr target
    - docker build -t my-app-image .
  dependencies:
    - compile
