
app:
  welcome:
    message: ${APP.WELCOME.MESSAGE:Hello, welcome to use the container.} 
  env: ${APP.ENV:local}
  token: ${APP.TOKEN:local token}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

internal-api:
  product:
    url: ${PRODUCT_HOST:http://localhost:8080}