name: '[Jar] Build Jar and Build Image and Push to Google Artifact Registry'

on:
  push:
    branches: [ "develop", "main" ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 這裡使用的是 Eclipse Temurin 的 JDK
          java-version: '17'
      # Step 3: 使用 Maven 建置專案
      - name: Build with Maven
        run: ./mvnw clean test
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 這裡使用的是 Eclipse Temurin 的 JDK
          java-version: '17'
      # Step 3: 使用 Maven 建置專案
      - name: Build with Maven
        run: ./mvnw verify -DnvdApiKey=${{ secrets.NVD_API_KEY }}

  build-jar:
    runs-on: ubuntu-latest
    needs: [ test, dependency-check ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 這裡使用的是 Eclipse Temurin 的 JDK
          java-version: '17'
      # Step 3: 使用 Maven 建置專案
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Upload the Jar
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: target/*.jar
